[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/aprovacao/:cliente/"
  to = "/aprovacao/:cliente/index.html"
  status = 200
